name: app_direct
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.6.2
  flutter:
    sdk: flutter
  flutter_sim_country_code: ^0.1.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3
  url_launcher_android: ^6.0.17
  external_app_launcher: ^3.0.0
  text_process:
    path: Plugin/text_process

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flags/
    - assets/countryCode/
